### ISSUE TITLE
Problem in blender 4.0

### ISSUE THREAD

**Issue by b4zz4** [SietseB/GP-Tool-Wheel#1]
I use this addons a lot and when updating I realized that it doesn't work. Sure changed the names of the palette and the way to register the addons:

to re-install:

```
Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 341, in enable
    importlib.reload(mod)
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bazza/.config/blender/4.0/scripts/addons/gp_tool_wheel/__init__.py", line 16, in <module>
    importlib.reload(tool_wheel_operator)
                     ^^^^^^^^^^^^^^^^^^^
NameError: name 'tool_wheel_operator' is not `defined`

to Used:

``


Python: Traceback (most recent call last):
  File "/home/bazza/.config/blender/4.0/scripts/addons/gp_tool_wheel/tool_wheel_operator.py", line 112, in invoke
    if not self.tool_wheel.prepare(event, area, context):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bazza/.config/blender/4.0/scripts/addons/gp_tool_wheel/tool_wheel_draw.py", line 262, in prepare
    self.text_color = wheel_colors.text
                          ^^^^^^^^^^^^^^
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_UNIFORM_COLOR'


```

**Comment by SietseB** [comment]
This should be resolved when you install [the latest release of the addon](https://github.com/SietseB/GP-Tool-Wheel/releases/tag/v1.0.4), version 1.0.4.
Copy `gp_tool_wheel` from the zipped archive to `/home/bazza/.config/blender/4.0/scripts/addons/gp_tool_wheel/`, start Blender and you should be good to go.
